apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mongodb
type: Opaque
data:
  root-password: ${MONGODB_ROOT_PASSWORD_BASE64}
  username: ${MONGODB_USERNAME_BASE64}
  password: ${MONGODB_PASSWORD_BASE64}
  database: ${MONGODB_DATABASE_BASE64} 