---
k3s_version: v1.30.2+k3s2
ansible_user: serveradmin  # Match your vCenter template VM user
systemd_dir: /etc/systemd/system
system_timezone: UTC

# Interface for k3s networking (match your vSphere VM interface)
flannel_iface: ens192

# Virtual IP for k3s API server
apiserver_endpoint: "10.77.250.220"

# Security token for k3s
k3s_token: "{{ lookup('env', 'K3S_TOKEN') | default('your-secure-token') }}"

# The IP on which the node is reachable
k3s_node_ip: "{{ ansible_facts[flannel_iface]['ipv4']['address'] }}"

# MetalLB configuration
metal_lb_type: native
metal_lb_mode: layer2
metal_lb_ip_range: "10.77.250.221-10.77.250.230"

# Extra arguments for k3s server
extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik

extra_agent_args: >-
  {{ extra_args }}

# kube-vip configuration
kube_vip_tag_version: v0.8.2
kube_vip_arp: true
kube_vip_iface: "{{ flannel_iface }}"

# Add these to your existing all.yml
postgresql_version: "14"
k3s_master_subnet: "10.77.250.0/24"  # Adjust based on your network
k3s_worker_subnet: "10.77.250.0/24"  # Adjust based on your network
postgresql_users:
  - name: k3s
    password: "{{ lookup('env', 'POSTGRES_PASSWORD') | default('changeMe') }}"
    db: k3s

# PostgreSQL Configuration
postgresql_host: "{{ hostvars[groups['postgresql_db'][0]]['ansible_host'] }}"
postgresql_port: 5432
postgresql_user: "{{ lookup('env', 'POSTGRES_USER') }}"
postgresql_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
postgresql_db: "{{ lookup('env', 'POSTGRES_DB') }}"