---
# PostgreSQL basic configuration
postgresql_version: "14"
postgresql_users: []
postgresql_host: "localhost"
postgresql_port: 5432
postgresql_user: "postgres"
postgresql_password: ""
postgresql_db: "postgres"

# PostgreSQL network configuration
postgresql_listen_addresses: '*'
postgresql_allowed_subnets:
  - "{{ master_subnet | default('10.77.250.0/24') }}"
  - "{{ k3s_worker_subnet | default('10.77.250.0/24') }}"
