version: '3'

services:
  backend:
    build:
      context: ./webapp/backend  # Set the context to the 'app' directory
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network
    volumes:
      - ./webapp/backend:/app  # Mount the 'app' folder
    environment:
      - FLASK_ENV=development

  frontend:
      build:
        context: ./webapp/frontend  # The frontend app's directory
        dockerfile: Dockerfile  # The Dockerfile should be in 'my-app'
      ports:
        - "3000:3000"  # Expose port 3000 for the frontend
      networks:
      - app-network
      volumes:
        - ./webapp/frontend:/app  # Mount the frontend code to the container
      command: npm run dev  # Run the Next.js app in development mode
      environment:
        - NODE_ENV=development
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    volumes:
      - ./docs:/docs
    ports:
      - "8000:8000"
    command: mkdocs serve -a 0.0.0.0:8000

networks:
  app-network:
    driver: bridge