---
k3s_server: true
k3s_control_plane: true
extra_server_args: ""
group_name_master: master

k3s_kubectl_binary: k3s kubectl

kube_vip_arp: true
kube_vip_iface:
kube_vip_cloud_provider_tag_version: main
kube_vip_tag_version: v0.7.2

kube_vip_bgp: false
kube_vip_bgp_routerid: 127.0.0.1
kube_vip_bgp_as: "64513"
kube_vip_bgp_peeraddress: 192.168.30.1
kube_vip_bgp_peeras: "64512"

kube_vip_bgp_peers: []
kube_vip_bgp_peers_groups: ['master']

metal_lb_controller_tag_version: v0.14.3
metal_lb_speaker_tag_version: v0.14.3
metal_lb_type: native

retry_count: 20

# yamllint disable rule:line-length
server_init_args: >-
  {% if inventory_hostname == groups[group_name_master][0] %}
    --cluster-init
    {{ extra_server_args }}
  {% else %}
    --server https://{{ apiserver_endpoint }}:6443
    --token {{ hostvars[groups[group_name_master][0]]['token'] }}
    {{ extra_server_args }}
  {% endif %}

systemd_dir: /etc/systemd/system

# Cilium configuration
cilium_bgp: false
cilium_iface: ~
