apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infrastructure components first
  - infrastructure/cert-manager
  - infrastructure/traefik
  # Applications after infrastructure
  - apps/webapp
  - apps/docs
  - apps/awx 