apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: "2.5.x"
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: flux-system
  install:
    createNamespace: true 