---
# First play: Build and verify images
- name: Build and Verify Images
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install required collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r collections/requirements.yml

    - name: Verify Docker daemon is running
      ansible.builtin.command:
        cmd: docker info
      register: docker_check
      failed_when: false
      changed_when: false

    - name: Fail if Docker is not running
      ansible.builtin.fail:
        msg: "Docker daemon is not running"
      when: docker_check.rc != 0

    - name: Build and Push Images
      ansible.builtin.include_tasks: tasks/build_images.yml
      
    - name: Verify Images Are Available
      ansible.builtin.command:
        cmd: docker image inspect {{ item }}
      register: image_check
      until: image_check.rc == 0
      retries: 5
      delay: 10
      with_items:
        - "{{ registry }}/webapp-frontend:{{ tag }}"
        - "{{ registry }}/webapp-backend:{{ tag }}"
      changed_when: false

# Import infrastructure deployment playbook
- import_playbook: deploy-vcenter.yml

# Import K3s deployment playbook
- import_playbook: site.yml

# Deploy Documentation
- name: Deploy Documentation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy Documentation
      block:
        - ansible.builtin.include_tasks: tasks/deploy_docs.yml
      rescue:
        - ansible.builtin.fail:
            msg: "Documentation deployment failed"