---
- name: Reset K3s Cluster
  hosts: all
  gather_facts: false
  roles:
    - role: reset
      become: true

- name: Reset K3s Cluster on vCenter
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy VMs using Terraform
      ansible.builtin.shell:
        cmd: |
          terraform init
          terraform destroy -auto-approve
        chdir: "{{ playbook_dir }}/../terraform/terraform-vm-provisioning"
      register: terraform_output