---
- name: Pre tasks
  hosts: all
  pre_tasks:
    - name: Verify Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.11', '>=')
        msg: "Ansible 2.11 or higher required"

- name: Setup PostgreSQL Database
  hosts: postgresql_db
  gather_facts: true
  roles:
    - role: postgresql
      become: true

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: prereq
      become: true
    - role: download
      become: true

- name: Setup k3s master
  hosts: k3s_master
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s control nodes
  hosts: k3s_control_nodes
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s workers
  hosts: k3s_workers
  roles:
    - role: k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: k3s_master
  roles:
    - role: k3s_server_post
      become: true
    - role: flux
      become: true

- name: Storing kubeconfig in the playbook directory
  hosts: k3s_master
  tasks:
    - name: Copying kubeconfig
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: ./kubeconfig
        flat: true
      when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']