site_name: Integration Automation System
docs_dir: docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Project Creation: user-guide/project-creation.md
    - Document Upload: user-guide/document-upload.md
  - Developer Guide:
    - Frontend Components: developer-guide/frontend.md
    - Database Schema: developer-guide/database.md
  - Infrastructure:
    - Terraform:
      - VM Provisioning: infrastructure/terraform/vm-provisioning.md
      - Network Setup: infrastructure/terraform/network-setup.md
  - Automation:
    - ZTP Setup: automation/ztp.md
    - Ansible:
      - Overview: automation/ansible/overview.md
      - Playbooks: automation/ansible/playbooks.md
      - Roles: automation/ansible/roles.md
      - Collections: automation/ansible/collections.md
    - Kubernetes:
      - K3s Setup: automation/kubernetes/k3s.md
      - Flux CD: automation/kubernetes/flux.md
      - Networking: automation/kubernetes/networking.md
  - Applications:
    - Overview: applications/overview.md
    - Frontend: applications/frontend.md
    - Backend: applications/backend.md
    - Databases:
      - PostgreSQL: applications/databases/postgresql.md
    - Network Services:
      - DHCP: applications/network/dhcp.md
      - TFTP: applications/network/tftp.md

# Coming Soon:
# - Network Configuration Guide
# - Architecture Documentation
# - API Reference
# - Documentation Generation Guide
