---
- name: Install PostgreSQL and dependencies
  ansible.builtin.apt:
    name: 
      - postgresql-{{ postgresql_version }}
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is started and enabled
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Configure PostgreSQL to listen on all addresses
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Configure client authentication
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    mode: '0640'
    owner: postgres
    group: postgres
  notify: restart postgresql

- name: Create PostgreSQL user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: LOGIN,CREATEDB
    state: present

- name: Create PostgreSQL database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgresql_db }}"
    owner: "{{ postgresql_user }}"
    state: present